services:
  postgres:
    image: postgres:17
    networks:
      - local
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: vinhdoan
      POSTGRES_DB: demo
      POSTGRES_DATA: /var/lib/postgresql/data
    ports:
      - 5435:5432
    volumes:
      - db:/var/lib/postgresql/data
networks:
  local:
    driver: bridge
volumes:
  db:
